swagger: '2.0'
info:
  title: delay insurance API
  description: 
  version: 1.0.0
host: '0.0.0.0:8088'
schemes:
  - http
basePath: /v1
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /policy:
    post:
      summary: 保单记账
      description: 保单记账
      tags:
        - Policy
      parameters:
        - name: PolicyReq
          in: body
          description: 保单记账
          required: true
          schema:
            $ref: '#/definitions/PolicyReq'
      responses:
        resultCode:
        	type: string
          description: 状态码（00代表成功，其它失败）
        errorDesc:
        	type: string
          description: 错误描述信息
  '/policy/{id}':
    get:
      summary: 保单查询
      description: 保单查询
      tags:
        - Policy
      parameters:
        - name: policyNo
          in: path
          description: 保单号
          type: string
          required: true
      responses:
          description: 返回保单详情
          schema:
            $ref: '#/definitions/PolicyRes'
  /flight:
    post:
      summary: 绑定航班记账
      description: 绑定航班记账
      tags:
        - Flight
      parameters:
        - name: FlightReq
          in: body
          description: 绑定航班记账
          required: true
          schema:
            $ref: '#/definitions/FlightReq'
      responses:
        resultCode:
        	type: string
          description: 状态码（00代表成功，其它失败）
        errorDesc:
        	type: string
          description: 错误描述信息
  '/flight/{id}':
    get:
      summary: 绑定航班查询
      description: 绑定航班查询
      tags:
        - Flight
      parameters:
        - name: policyNo
          in: path
          description: 保单号
          type: string
          required: true
      responses:
          description: 返回航班绑定详情
          schema:
            $ref: '#/definitions/FlightRes'
  /claim:
    post:
      summary: 理赔记账
      description: 理赔记账
      tags:
        - Claim
      parameters:
        - name: ClaimReq
          in: body
          description: 理赔记账
          required: true
          schema:
            $ref: '#/definitions/ClaimReq'
      responses:
        resultCode:
        	type: string
          description: 状态码（00代表成功，其它失败）
        errorDesc:
        	type: string
          description: 错误描述信息
  '/claim/{id}':
    get:
      summary: 理赔信息查询
      description: 理赔信息查询
      tags:
        - Claim
      parameters:
        - name: policyNo
          in: path
          description: 保单号
          type: string
          required: true
      responses:
          description: 返回理赔详情
          schema:
            $ref: '#/definitions/ClaimRes'
definitions:
  PolicyReq:
    type: object
      properties:
        openId:
          type: string
          description: 用户的openId
        policyInfo:
          $ref: '#/definitions/PolicyInfo'
          description: 保单信息
        orderInfo:
          $ref: '#/definitions/OrderInfo'
          description: 订单信息
  PolicyRes:
    type: object
    properties:
      openId:
        type: string
        description: 用户的openId
      policyInfo:
        $ref: '#/definitions/PolicyInfo'
        description: 保单信息
      orderInfo:
        $ref: '#/definitions/OrderInfo'
        description: 订单信息
      resultCode:
      	type: string
        description: 状态码（00代表成功，其它失败）
      errorDesc:
        type: string
        description: 错误描述信息
  OrderInfo:
    type: Object
    properties:
      orderNo:
        type: string
        description: 订单号
      productId:
        type: string
        description: 云产品Id
      planId:
        type: string
        description: 产险产品Id
      packageId:
        type: string
        description: 套餐Id
      applicantName:
        type: string
        description: 投保人姓名
      applicantPhone:
        type: string
        description: 投保人电话
      applicantCertificateNo:
        type: string
        description: 投保人证件号码
  PolicyInfo:
    type: Object
    properties:
	  policyNo:
	    type: string
	    description: 保单号
	  insuranceBeginDate:
	    type: string
	    description: 保险起期
	  insuranceEndDate:
	    type: string
	    description: 保险止期
  FlightReq:
    type: object
    properties:
      openId:
        type: string
        description: 用户的openId
	  policyNo:
	    type: string
	    description: 保单号
      flightInfo:
        type: array
        description: 航班信息
        items:
          $ref: '#/definitions/FlightInfo'
  FlightRes:
    type: object
    properties:
    	openId:
        type: string
        description: 用户的openId
			policyNo:
				type:string
				description: 保单号
      flightInfo:
        type: array
        description: 航班信息
        items:
          $ref: '#/definitions/FlightInfo'
      resultCode:
      	type: string
        description: 状态码（00代表成功，其它失败）
      errorDesc:
        type: string
        description: 错误描述信息
  FlightInfo:
    type: Object
    properties:
      flightNo:
	    type: string
	    description: 航班号
	  sectorNo:
	    type: string
	    description: 航段号
	  planedDepartureTime:
	    type: string
	    description: 计划起飞时间
	  planedArrivalTime:
	    type: string
	    description: 计划到达时间
	ClaimReq:
    type: object
    properties:
    	openId:
        type: string
        description: 用户的openId
			policyNo:
				type:string
				description: 保单号
      claimInfo:
        type: array
        description: 理赔信息
        items:
          $ref: '#/definitions/ClaimInfo'
    ClaimRes:
    type: object
    properties:
    	openId:
        type: string
        description: 用户的openId
			policyNo:
				type:string
				description: 保单号
      claimInfo:
        type: array
        description: 理赔信息
        items:
          $ref: '#/definitions/ClaimInfo'
      resultCode:
      	type: string
        description: 状态码（00代表成功，其它失败）
      errorDesc:
        type: string
        description: 错误描述信息
	ClaimInfo:
	  type: Object
	  properties:
	    flightNo:
	      type: string
		  description: 航班号
	    sectorNo:
		  type: string
		  description: 航段号
	    planedDepartureTime:
		  type: string
		  description: 计划起飞时间
	    planedArrivalTime:
		  type: string
		  description: 计划到达时间
	    actualDepartureTime:
		  type: string
		  description: 实际起飞时间
	    actualArrivalTime:
		  type: string
		  description: 实际到达时间
	    flightState:
		  type: integer
		  description: 航班状态（0：无需赔付 1：已延误，2：已取消，3：已返航）
	    claimAmount:
          type: number
          format: double
          description: 理赔金额
        claimPaymentState:
          type: integer
          description: 赔付状态（0：未赔付，1：成功赔付，2：赔付失败）